from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    AddCategoryView,
    confirmation_view,
    contact, 
    about,
    AddPostView,
    DeletePostView,
    HomeView,
    ArticleDetailView,
    UpdatePostView,
    CategoryView,
    CategoryListView,
    LikeView,
    galery,
    search_articles,
    AddCommentView,
    author_profile,
    like_comment,
)

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('add_post/', login_required(AddPostView.as_view()), name='add_post'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article-detail'),
    path('article/edit/<int:pk>/', login_required(UpdatePostView.as_view()), name='update_post'),
    path('article/<int:pk>/remove/', login_required(DeletePostView.as_view()), name='delete_post'),
    path('add_category/', login_required(AddCategoryView.as_view()), name='add_category'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('category/<str:cats>/', CategoryView, name='category'),
    path('category-list/', CategoryListView, name='category-list'),
    path('like/<int:pk>/', LikeView, name='like_post'),
    path('article/<int:pk>/comment/', login_required(AddCommentView.as_view()), name='add_comment'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    path('galery/', galery, name='galery'),
    path('search/', search_articles, name='search_articles'),
    path('confirmation/', confirmation_view, name='confirmation'),
    path('author/<int:user_id>/', author_profile, name='author_profile'),
    path('comment/<int:pk>/like/', like_comment, name='like_comment'),
]